const bus = require('../model/bus')

function strToTimeSpan(timeString) {
    //const timeString = "6:15 AM";
    const ISTOffset = 330; // IST is UTC+5:30

    const date = new Date(`January 1, 1970 ${timeString} UTC+0000`);
    const timestamp = date.getTime() + (ISTOffset * 60 * 1000);
    return timestamp
}
let x = [
    { startTime: "6:30 AM", endTime: "10:15 AM" },
    { startTime: "12:15 PM", endTime: "4:00 PM" },
    { startTime: "8:45 AM", endTime: "12:05 PM" },
    { startTime: "7:30 AM", endTime: "12:15 PM" },
    { startTime: "1:30 PM", endTime: "7:15 PM" },
    { startTime: "1:30 AM", endTime: "8:00 AM" },
    { startTime: "11:30 AM", endTime: "4:15 PM" },
    { startTime: "8:00 AM", endTime: "12:15 PM" },
    { startTime: "2:30 PM", endTime: "7:15 PM" },
    { startTime: "7:30 AM", endTime: "1:15 PM" },
]

let data = [
    {
        name: 'IntrCity Smart Bus',
        category: 'A/C Sleeper (2+1)',
        totalSeats: 38,
        totalWindowSeatsAvailable: 24,
        rating: 4.7,
        animeties: ['Live Tracking', 'Policies', 'Photos', 'Amenities', 'Reviews'],
        "seats_details": [
            { no: 1, type: 'UW', price: 900, is_reseved: false, is_clicked: false },
            { no: 2, type: 'UW', price: 900, is_reseved: false, is_clicked: false },
            { no: 3, type: 'UW', price: 900, is_reseved: false, is_clicked: false },
            { no: 4, type: 'UW', price: 900, is_reseved: false, is_clicked: false },
            { no: 5, type: 'UW', price: 900, is_reseved: false, is_clicked: false },
            { no: 6, type: 'UW', price: 900, is_reseved: false, is_clicked: false },
            { no: 7, type: 'UW', price: 900, is_reseved: false, is_clicked: false },
            { no: 8, type: 'US', price: 790, is_reseved: false, is_clicked: false },
            { no: 9, type: 'US', price: 790, is_reseved: false, is_clicked: false },
            { no: 10, type: 'US', price: 790, is_reseved: false, is_clicked: false },
            { no: 11, type: 'US', price: 790, is_reseved: false, is_clicked: false },
            { no: 12, type: 'US', price: 790, is_reseved: false, is_clicked: false },
            { no: 13, type: 'US', price: 790, is_reseved: false, is_clicked: false },
            { no: 14, type: 'US', price: 790, is_reseved: false, is_clicked: false },
            { no: 15, type: 'UW', price: 900, is_reseved: false, is_clicked: false },
            { no: 16, type: 'UW', price: 900, is_reseved: false, is_clicked: false },
            { no: 17, type: 'UW', price: 900, is_reseved: false, is_clicked: false },
            { no: 18, type: 'UW', price: 900, is_reseved: false, is_clicked: false },
            { no: 19, type: 'UW', price: 900, is_reseved: false, is_clicked: false },
            { no: 20, type: 'LW', price: 860, is_reseved: false, is_clicked: false },
            { no: 21, type: 'LW', price: 860, is_reseved: false, is_clicked: false },
            { no: 22, type: 'LW', price: 860, is_reseved: false, is_clicked: false },
            { no: 23, type: 'LW', price: 860, is_reseved: false, is_clicked: false },
            { no: 24, type: 'LW', price: 860, is_reseved: false, is_clicked: false },
            { no: 25, type: 'LW', price: 860, is_reseved: false, is_clicked: false },
            { no: 26, type: 'LW', price: 860, is_reseved: false, is_clicked: false },
            { no: 27, type: 'LS', price: 720, is_reseved: false, is_clicked: false },
            { no: 28, type: 'LS', price: 720, is_reseved: false, is_clicked: false },
            { no: 29, type: 'LS', price: 720, is_reseved: false, is_clicked: false },
            { no: 30, type: 'LS', price: 720, is_reseved: false, is_clicked: false },
            { no: 31, type: 'LS', price: 720, is_reseved: false, is_clicked: false },
            { no: 32, type: 'LS', price: 720, is_reseved: false, is_clicked: false },
            { no: 33, type: 'LS', price: 720, is_reseved: false, is_clicked: false },
            { no: 34, type: 'LW', price: 860, is_reseved: false, is_clicked: false },
            { no: 35, type: 'LW', price: 860, is_reseved: false, is_clicked: false },
            { no: 36, type: 'LW', price: 860, is_reseved: false, is_clicked: false },
            { no: 37, type: 'LW', price: 860, is_reseved: false, is_clicked: false },
            { no: 38, type: 'LW', price: 860, is_reseved: false, is_clicked: false }
        ]

    },

    {

        name: 'Tata Motors - Marcopolo',
        category: 'A/C Sleeper (2+1)',
        totalSeats: 38,
        totalWindowSeatsAvailable: 24,
        rating: 4.7,
        animeties: ['Live Tracking', 'Policies', 'Photos', 'Amenities', 'Reviews'],
        "seats_details": [
            { no: 1, type: 'UW', price: 1000, is_reseved: false, is_clicked: false },
            { no: 2, type: 'UW', price: 1000, is_reseved: false, is_clicked: false },
            { no: 3, type: 'UW', price: 1000, is_reseved: false, is_clicked: false },
            { no: 4, type: 'UW', price: 1000, is_reseved: false, is_clicked: false },
            { no: 5, type: 'UW', price: 1000, is_reseved: false, is_clicked: false },
            { no: 6, type: 'UW', price: 1000, is_reseved: false, is_clicked: false },
            { no: 7, type: 'UW', price: 1000, is_reseved: false, is_clicked: false },
            { no: 8, type: 'US', price: 800, is_reseved: false, is_clicked: false },
            { no: 9, type: 'US', price: 800, is_reseved: false, is_clicked: false },
            { no: 10, type: 'US', price: 800, is_reseved: false, is_clicked: false },
            { no: 11, type: 'US', price: 800, is_reseved: false, is_clicked: false },
            { no: 12, type: 'US', price: 800, is_reseved: false, is_clicked: false },
            { no: 13, type: 'US', price: 800, is_reseved: false, is_clicked: false },
            { no: 14, type: 'US', price: 800, is_reseved: false, is_clicked: false },
            { no: 15, type: 'UW', price: 1000, is_reseved: false, is_clicked: false },
            { no: 16, type: 'UW', price: 1000, is_reseved: false, is_clicked: false },
            { no: 17, type: 'UW', price: 1000, is_reseved: false, is_clicked: false },
            { no: 18, type: 'UW', price: 1000, is_reseved: false, is_clicked: false },
            { no: 19, type: 'UW', price: 1000, is_reseved: false, is_clicked: false },
            { no: 20, type: 'LW', price: 950, is_reseved: false, is_clicked: false },
            { no: 21, type: 'LW', price: 950, is_reseved: false, is_clicked: false },
            { no: 22, type: 'LW', price: 950, is_reseved: false, is_clicked: false },
            { no: 23, type: 'LW', price: 950, is_reseved: false, is_clicked: false },
            { no: 24, type: 'LW', price: 950, is_reseved: false, is_clicked: false },
            { no: 25, type: 'LW', price: 950, is_reseved: false, is_clicked: false },
            { no: 26, type: 'LW', price: 950, is_reseved: false, is_clicked: false },
            { no: 27, type: 'LS', price: 770, is_reseved: false, is_clicked: false },
            { no: 28, type: 'LS', price: 770, is_reseved: false, is_clicked: false },
            { no: 29, type: 'LS', price: 770, is_reseved: false, is_clicked: false },
            { no: 30, type: 'LS', price: 770, is_reseved: false, is_clicked: false },
            { no: 31, type: 'LS', price: 770, is_reseved: false, is_clicked: false },
            { no: 32, type: 'LS', price: 770, is_reseved: false, is_clicked: false },
            { no: 33, type: 'LS', price: 770, is_reseved: false, is_clicked: false },
            { no: 34, type: 'LW', price: 950, is_reseved: false, is_clicked: false },
            { no: 35, type: 'LW', price: 950, is_reseved: false, is_clicked: false },
            { no: 36, type: 'LW', price: 950, is_reseved: false, is_clicked: false },
            { no: 37, type: 'LW', price: 950, is_reseved: false, is_clicked: false },
            { no: 38, type: 'LW', price: 950, is_reseved: false, is_clicked: false }
        ]
    },
    {
        name: 'Eicher Motors',
        category: 'A/C Sleeper (2+1)',
        totalSeats: 38,
        totalWindowSeatsAvailable: 24,
        rating: 4.5,
        animeties: ['Live Tracking', 'Policies', 'Photos', 'Amenities', 'Reviews'],
        "seats_details": [
            { no: 1, type: 'UW', price: 950, is_reseved: false, is_clicked: false },
            { no: 2, type: 'UW', price: 950, is_reseved: false, is_clicked: false },
            { no: 3, type: 'UW', price: 950, is_reseved: false, is_clicked: false },
            { no: 4, type: 'UW', price: 950, is_reseved: false, is_clicked: false },
            { no: 5, type: 'UW', price: 950, is_reseved: false, is_clicked: false },
            { no: 6, type: 'UW', price: 950, is_reseved: false, is_clicked: false },
            { no: 7, type: 'UW', price: 950, is_reseved: false, is_clicked: false },
            { no: 8, type: 'US', price: 800, is_reseved: false, is_clicked: false },
            { no: 9, type: 'US', price: 800, is_reseved: false, is_clicked: false },
            { no: 10, type: 'US', price: 800, is_reseved: false, is_clicked: false },
            { no: 11, type: 'US', price: 800, is_reseved: false, is_clicked: false },
            { no: 12, type: 'US', price: 800, is_reseved: false, is_clicked: false },
            { no: 13, type: 'US', price: 800, is_reseved: false, is_clicked: false },
            { no: 14, type: 'US', price: 800, is_reseved: false, is_clicked: false },
            { no: 15, type: 'UW', price: 950, is_reseved: false, is_clicked: false },
            { no: 16, type: 'UW', price: 950, is_reseved: false, is_clicked: false },
            { no: 17, type: 'UW', price: 950, is_reseved: false, is_clicked: false },
            { no: 18, type: 'UW', price: 950, is_reseved: false, is_clicked: false },
            { no: 19, type: 'UW', price: 950, is_reseved: false, is_clicked: false },
            { no: 20, type: 'LW', price: 950, is_reseved: false, is_clicked: false },
            { no: 21, type: 'LW', price: 950, is_reseved: false, is_clicked: false },
            { no: 22, type: 'LW', price: 950, is_reseved: false, is_clicked: false },
            { no: 23, type: 'LW', price: 950, is_reseved: false, is_clicked: false },
            { no: 24, type: 'LW', price: 950, is_reseved: false, is_clicked: false },
            { no: 25, type: 'LW', price: 950, is_reseved: false, is_clicked: false },
            { no: 26, type: 'LW', price: 950, is_reseved: false, is_clicked: false },
            { no: 27, type: 'LS', price: 750, is_reseved: false, is_clicked: false },
            { no: 28, type: 'LS', price: 750, is_reseved: false, is_clicked: false },
            { no: 29, type: 'LS', price: 750, is_reseved: false, is_clicked: false },
            { no: 30, type: 'LS', price: 750, is_reseved: false, is_clicked: false },
            { no: 31, type: 'LS', price: 750, is_reseved: false, is_clicked: false },
            { no: 32, type: 'LS', price: 750, is_reseved: false, is_clicked: false },
            { no: 33, type: 'LS', price: 750, is_reseved: false, is_clicked: false },
            { no: 34, type: 'LW', price: 950, is_reseved: false, is_clicked: false },
            { no: 35, type: 'LW', price: 950, is_reseved: false, is_clicked: false },
            { no: 36, type: 'LW', price: 950, is_reseved: false, is_clicked: false },
            { no: 37, type: 'LW', price: 950, is_reseved: false, is_clicked: false },
            { no: 38, type: 'LW', price: 950, is_reseved: false, is_clicked: false }
        ]
    },
    {

        name: 'BharatBenz',
        category: 'A/C Sleeper (2+1)',
        totalSeats: 38,
        totalWindowSeatsAvailable: 24,
        rating: 4.5,
        animeties: ['Live Tracking', 'Policies', 'Photos', 'Amenities', 'Reviews'],
        "seats_details": [
            { no: 1, type: 'UW', price: 1050, is_reseved: false, is_clicked: false },
            { no: 2, type: 'UW', price: 1050, is_reseved: false, is_clicked: false },
            { no: 3, type: 'UW', price: 1050, is_reseved: false, is_clicked: false },
            { no: 4, type: 'UW', price: 1050, is_reseved: false, is_clicked: false },
            { no: 5, type: 'UW', price: 1050, is_reseved: false, is_clicked: false },
            { no: 6, type: 'UW', price: 1050, is_reseved: false, is_clicked: false },
            { no: 7, type: 'UW', price: 1050, is_reseved: false, is_clicked: false },
            { no: 8, type: 'US', price: 900, is_reseved: false, is_clicked: false },
            { no: 9, type: 'US', price: 900, is_reseved: false, is_clicked: false },
            { no: 10, type: 'US', price: 900, is_reseved: false, is_clicked: false },
            { no: 11, type: 'US', price: 900, is_reseved: false, is_clicked: false },
            { no: 12, type: 'US', price: 900, is_reseved: false, is_clicked: false },
            { no: 13, type: 'US', price: 900, is_reseved: false, is_clicked: false },
            { no: 14, type: 'US', price: 900, is_reseved: false, is_clicked: false },
            { no: 15, type: 'UW', price: 1050, is_reseved: false, is_clicked: false },
            { no: 16, type: 'UW', price: 1050, is_reseved: false, is_clicked: false },
            { no: 17, type: 'UW', price: 1050, is_reseved: false, is_clicked: false },
            { no: 18, type: 'UW', price: 1050, is_reseved: false, is_clicked: false },
            { no: 19, type: 'UW', price: 1050, is_reseved: false, is_clicked: false },
            { no: 20, type: 'LW', price: 1050, is_reseved: false, is_clicked: false },
            { no: 21, type: 'LW', price: 1050, is_reseved: false, is_clicked: false },
            { no: 22, type: 'LW', price: 1050, is_reseved: false, is_clicked: false },
            { no: 23, type: 'LW', price: 1050, is_reseved: false, is_clicked: false },
            { no: 24, type: 'LW', price: 1050, is_reseved: false, is_clicked: false },
            { no: 25, type: 'LW', price: 1050, is_reseved: false, is_clicked: false },
            { no: 26, type: 'LW', price: 1050, is_reseved: false, is_clicked: false },
            { no: 27, type: 'LS', price: 800, is_reseved: false, is_clicked: false },
            { no: 28, type: 'LS', price: 800, is_reseved: false, is_clicked: false },
            { no: 29, type: 'LS', price: 800, is_reseved: false, is_clicked: false },
            { no: 30, type: 'LS', price: 800, is_reseved: false, is_clicked: false },
            { no: 31, type: 'LS', price: 800, is_reseved: false, is_clicked: false },
            { no: 32, type: 'LS', price: 800, is_reseved: false, is_clicked: false },
            { no: 33, type: 'LS', price: 800, is_reseved: false, is_clicked: false },
            { no: 34, type: 'LW', price: 1050, is_reseved: false, is_clicked: false },
            { no: 35, type: 'LW', price: 1050, is_reseved: false, is_clicked: false },
            { no: 36, type: 'LW', price: 1050, is_reseved: false, is_clicked: false },
            { no: 37, type: 'LW', price: 1050, is_reseved: false, is_clicked: false },
            { no: 38, type: 'LW', price: 1050, is_reseved: false, is_clicked: false }
        ]
    },
    {
        name: 'Volvo Buses',
        category: 'A/C Sleeper (2+1)',
        totalSeats: 38,
        totalWindowSeatsAvailable: 24,
        rating: 4.5,
        animeties: ['Live Tracking', 'Policies', 'Photos', 'Amenities', 'Reviews'],
        "seats_details": [
            { no: 1, type: 'UW', price: 900, is_reseved: false, is_clicked: false },
            { no: 2, type: 'UW', price: 900, is_reseved: false, is_clicked: false },
            { no: 3, type: 'UW', price: 900, is_reseved: false, is_clicked: false },
            { no: 4, type: 'UW', price: 900, is_reseved: false, is_clicked: false },
            { no: 5, type: 'UW', price: 900, is_reseved: false, is_clicked: false },
            { no: 6, type: 'UW', price: 900, is_reseved: false, is_clicked: false },
            { no: 7, type: 'UW', price: 900, is_reseved: false, is_clicked: false },
            { no: 8, type: 'US', price: 790, is_reseved: false, is_clicked: false },
            { no: 9, type: 'US', price: 790, is_reseved: false, is_clicked: false },
            { no: 10, type: 'US', price: 790, is_reseved: false, is_clicked: false },
            { no: 11, type: 'US', price: 790, is_reseved: false, is_clicked: false },
            { no: 12, type: 'US', price: 790, is_reseved: false, is_clicked: false },
            { no: 13, type: 'US', price: 790, is_reseved: false, is_clicked: false },
            { no: 14, type: 'US', price: 790, is_reseved: false, is_clicked: false },
            { no: 15, type: 'UW', price: 900, is_reseved: false, is_clicked: false },
            { no: 16, type: 'UW', price: 900, is_reseved: false, is_clicked: false },
            { no: 17, type: 'UW', price: 900, is_reseved: false, is_clicked: false },
            { no: 18, type: 'UW', price: 900, is_reseved: false, is_clicked: false },
            { no: 19, type: 'UW', price: 900, is_reseved: false, is_clicked: false },
            { no: 20, type: 'LW', price: 860, is_reseved: false, is_clicked: false },
            { no: 21, type: 'LW', price: 860, is_reseved: false, is_clicked: false },
            { no: 22, type: 'LW', price: 860, is_reseved: false, is_clicked: false },
            { no: 23, type: 'LW', price: 860, is_reseved: false, is_clicked: false },
            { no: 24, type: 'LW', price: 860, is_reseved: false, is_clicked: false },
            { no: 25, type: 'LW', price: 860, is_reseved: false, is_clicked: false },
            { no: 26, type: 'LW', price: 860, is_reseved: false, is_clicked: false },
            { no: 27, type: 'LS', price: 720, is_reseved: false, is_clicked: false },
            { no: 28, type: 'LS', price: 720, is_reseved: false, is_clicked: false },
            { no: 29, type: 'LS', price: 720, is_reseved: false, is_clicked: false },
            { no: 30, type: 'LS', price: 720, is_reseved: false, is_clicked: false },
            { no: 31, type: 'LS', price: 720, is_reseved: false, is_clicked: false },
            { no: 32, type: 'LS', price: 720, is_reseved: false, is_clicked: false },
            { no: 33, type: 'LS', price: 720, is_reseved: false, is_clicked: false },
            { no: 34, type: 'LW', price: 860, is_reseved: false, is_clicked: false },
            { no: 35, type: 'LW', price: 860, is_reseved: false, is_clicked: false },
            { no: 36, type: 'LW', price: 860, is_reseved: false, is_clicked: false },
            { no: 37, type: 'LW', price: 860, is_reseved: false, is_clicked: false },
            { no: 38, type: 'LW', price: 860, is_reseved: false, is_clicked: false }
        ]
    },
    {
        name: 'Mahindra & Mahindra',
        category: 'A/C Sleeper (2+1)',
        totalSeats: 38,
        totalWindowSeatsAvailable: 24,
        rating: 4.5,
        animeties: ['Live Tracking', 'Policies', 'Photos', 'Amenities', 'Reviews'],
        "seats_details": [
            { no: 1, type: 'UW', price: 990, is_reseved: false, is_clicked: false },
            { no: 2, type: 'UW', price: 990, is_reseved: false, is_clicked: false },
            { no: 3, type: 'UW', price: 990, is_reseved: false, is_clicked: false },
            { no: 4, type: 'UW', price: 990, is_reseved: false, is_clicked: false },
            { no: 5, type: 'UW', price: 990, is_reseved: false, is_clicked: false },
            { no: 6, type: 'UW', price: 990, is_reseved: false, is_clicked: false },
            { no: 7, type: 'UW', price: 990, is_reseved: false, is_clicked: false },
            { no: 8, type: 'US', price: 790, is_reseved: false, is_clicked: false },
            { no: 9, type: 'US', price: 790, is_reseved: false, is_clicked: false },
            { no: 10, type: 'US', price: 790, is_reseved: false, is_clicked: false },
            { no: 11, type: 'US', price: 790, is_reseved: false, is_clicked: false },
            { no: 12, type: 'US', price: 790, is_reseved: false, is_clicked: false },
            { no: 13, type: 'US', price: 790, is_reseved: false, is_clicked: false },
            { no: 14, type: 'US', price: 790, is_reseved: false, is_clicked: false },
            { no: 15, type: 'UW', price: 990, is_reseved: false, is_clicked: false },
            { no: 16, type: 'UW', price: 990, is_reseved: false, is_clicked: false },
            { no: 17, type: 'UW', price: 990, is_reseved: false, is_clicked: false },
            { no: 18, type: 'UW', price: 990, is_reseved: false, is_clicked: false },
            { no: 19, type: 'UW', price: 990, is_reseved: false, is_clicked: false },
            { no: 20, type: 'LW', price: 990, is_reseved: false, is_clicked: false },
            { no: 21, type: 'LW', price: 990, is_reseved: false, is_clicked: false },
            { no: 22, type: 'LW', price: 990, is_reseved: false, is_clicked: false },
            { no: 23, type: 'LW', price: 990, is_reseved: false, is_clicked: false },
            { no: 24, type: 'LW', price: 990, is_reseved: false, is_clicked: false },
            { no: 25, type: 'LW', price: 990, is_reseved: false, is_clicked: false },
            { no: 26, type: 'LW', price: 990, is_reseved: false, is_clicked: false },
            { no: 27, type: 'LS', price: 690, is_reseved: false, is_clicked: false },
            { no: 28, type: 'LS', price: 690, is_reseved: false, is_clicked: false },
            { no: 29, type: 'LS', price: 690, is_reseved: false, is_clicked: false },
            { no: 30, type: 'LS', price: 690, is_reseved: false, is_clicked: false },
            { no: 31, type: 'LS', price: 690, is_reseved: false, is_clicked: false },
            { no: 32, type: 'LS', price: 690, is_reseved: false, is_clicked: false },
            { no: 33, type: 'LS', price: 690, is_reseved: false, is_clicked: false },
            { no: 34, type: 'LW', price: 990, is_reseved: false, is_clicked: false },
            { no: 35, type: 'LW', price: 990, is_reseved: false, is_clicked: false },
            { no: 36, type: 'LW', price: 990, is_reseved: false, is_clicked: false },
            { no: 37, type: 'LW', price: 990, is_reseved: false, is_clicked: false },
            { no: 38, type: 'LW', price: 990, is_reseved: false, is_clicked: false }
        ]
    },
    {
        name: 'Ashok Leyland',
        category: 'A/C Sleeper (2+1)',
        totalSeats: 38,
        totalWindowSeatsAvailable: 24,
        rating: 4.5,
        animeties: ['Live Tracking', 'Policies', 'Photos', 'Amenities', 'Reviews'],
        "seats_details": [
            { no: 1, type: 'UW', price: 1000, is_reseved: false, is_clicked: false },
            { no: 2, type: 'UW', price: 1000, is_reseved: false, is_clicked: false },
            { no: 3, type: 'UW', price: 1000, is_reseved: false, is_clicked: false },
            { no: 4, type: 'UW', price: 1000, is_reseved: false, is_clicked: false },
            { no: 5, type: 'UW', price: 1000, is_reseved: false, is_clicked: false },
            { no: 6, type: 'UW', price: 1000, is_reseved: false, is_clicked: false },
            { no: 7, type: 'UW', price: 1000, is_reseved: false, is_clicked: false },
            { no: 8, type: 'US', price: 800, is_reseved: false, is_clicked: false },
            { no: 9, type: 'US', price: 800, is_reseved: false, is_clicked: false },
            { no: 10, type: 'US', price: 800, is_reseved: false, is_clicked: false },
            { no: 11, type: 'US', price: 800, is_reseved: false, is_clicked: false },
            { no: 12, type: 'US', price: 800, is_reseved: false, is_clicked: false },
            { no: 13, type: 'US', price: 800, is_reseved: false, is_clicked: false },
            { no: 14, type: 'US', price: 800, is_reseved: false, is_clicked: false },
            { no: 15, type: 'UW', price: 1000, is_reseved: false, is_clicked: false },
            { no: 16, type: 'UW', price: 1000, is_reseved: false, is_clicked: false },
            { no: 17, type: 'UW', price: 1000, is_reseved: false, is_clicked: false },
            { no: 18, type: 'UW', price: 1000, is_reseved: false, is_clicked: false },
            { no: 19, type: 'UW', price: 1000, is_reseved: false, is_clicked: false },
            { no: 20, type: 'LW', price: 950, is_reseved: false, is_clicked: false },
            { no: 21, type: 'LW', price: 950, is_reseved: false, is_clicked: false },
            { no: 22, type: 'LW', price: 950, is_reseved: false, is_clicked: false },
            { no: 23, type: 'LW', price: 950, is_reseved: false, is_clicked: false },
            { no: 24, type: 'LW', price: 950, is_reseved: false, is_clicked: false },
            { no: 25, type: 'LW', price: 950, is_reseved: false, is_clicked: false },
            { no: 26, type: 'LW', price: 950, is_reseved: false, is_clicked: false },
            { no: 27, type: 'LS', price: 770, is_reseved: false, is_clicked: false },
            { no: 28, type: 'LS', price: 770, is_reseved: false, is_clicked: false },
            { no: 29, type: 'LS', price: 770, is_reseved: false, is_clicked: false },
            { no: 30, type: 'LS', price: 770, is_reseved: false, is_clicked: false },
            { no: 31, type: 'LS', price: 770, is_reseved: false, is_clicked: false },
            { no: 32, type: 'LS', price: 770, is_reseved: false, is_clicked: false },
            { no: 33, type: 'LS', price: 770, is_reseved: false, is_clicked: false },
            { no: 34, type: 'LW', price: 950, is_reseved: false, is_clicked: false },
            { no: 35, type: 'LW', price: 950, is_reseved: false, is_clicked: false },
            { no: 36, type: 'LW', price: 950, is_reseved: false, is_clicked: false },
            { no: 37, type: 'LW', price: 950, is_reseved: false, is_clicked: false },
            { no: 38, type: 'LW', price: 950, is_reseved: false, is_clicked: false }
        ]
    },
    {
        name: 'Jabbar Travels',
        category: 'A/C Sleeper (2+1)',
        totalSeats: 38,
        totalWindowSeatsAvailable: 24,
        rating: 4.5,
        animeties: ['Live Tracking', 'Policies', 'Photos', 'Amenities', 'Reviews'],
        "seats_details": [
            { no: 1, type: 'UW', price: 950, is_reseved: false, is_clicked: false },
            { no: 2, type: 'UW', price: 950, is_reseved: false, is_clicked: false },
            { no: 3, type: 'UW', price: 950, is_reseved: false, is_clicked: false },
            { no: 4, type: 'UW', price: 950, is_reseved: false, is_clicked: false },
            { no: 5, type: 'UW', price: 950, is_reseved: false, is_clicked: false },
            { no: 6, type: 'UW', price: 950, is_reseved: false, is_clicked: false },
            { no: 7, type: 'UW', price: 950, is_reseved: false, is_clicked: false },
            { no: 8, type: 'US', price: 800, is_reseved: false, is_clicked: false },
            { no: 9, type: 'US', price: 800, is_reseved: false, is_clicked: false },
            { no: 10, type: 'US', price: 800, is_reseved: false, is_clicked: false },
            { no: 11, type: 'US', price: 800, is_reseved: false, is_clicked: false },
            { no: 12, type: 'US', price: 800, is_reseved: false, is_clicked: false },
            { no: 13, type: 'US', price: 800, is_reseved: false, is_clicked: false },
            { no: 14, type: 'US', price: 800, is_reseved: false, is_clicked: false },
            { no: 15, type: 'UW', price: 950, is_reseved: false, is_clicked: false },
            { no: 16, type: 'UW', price: 950, is_reseved: false, is_clicked: false },
            { no: 17, type: 'UW', price: 950, is_reseved: false, is_clicked: false },
            { no: 18, type: 'UW', price: 950, is_reseved: false, is_clicked: false },
            { no: 19, type: 'UW', price: 950, is_reseved: false, is_clicked: false },
            { no: 20, type: 'LW', price: 950, is_reseved: false, is_clicked: false },
            { no: 21, type: 'LW', price: 950, is_reseved: false, is_clicked: false },
            { no: 22, type: 'LW', price: 950, is_reseved: false, is_clicked: false },
            { no: 23, type: 'LW', price: 950, is_reseved: false, is_clicked: false },
            { no: 24, type: 'LW', price: 950, is_reseved: false, is_clicked: false },
            { no: 25, type: 'LW', price: 950, is_reseved: false, is_clicked: false },
            { no: 26, type: 'LW', price: 950, is_reseved: false, is_clicked: false },
            { no: 27, type: 'LS', price: 750, is_reseved: false, is_clicked: false },
            { no: 28, type: 'LS', price: 750, is_reseved: false, is_clicked: false },
            { no: 29, type: 'LS', price: 750, is_reseved: false, is_clicked: false },
            { no: 30, type: 'LS', price: 750, is_reseved: false, is_clicked: false },
            { no: 31, type: 'LS', price: 750, is_reseved: false, is_clicked: false },
            { no: 32, type: 'LS', price: 750, is_reseved: false, is_clicked: false },
            { no: 33, type: 'LS', price: 750, is_reseved: false, is_clicked: false },
            { no: 34, type: 'LW', price: 950, is_reseved: false, is_clicked: false },
            { no: 35, type: 'LW', price: 950, is_reseved: false, is_clicked: false },
            { no: 36, type: 'LW', price: 950, is_reseved: false, is_clicked: false },
            { no: 37, type: 'LW', price: 950, is_reseved: false, is_clicked: false },
            { no: 38, type: 'LW', price: 950, is_reseved: false, is_clicked: false }
        ]
    },
    {
        name: 'Jeppiaar Travels',
        category: 'A/C Sleeper (2+1)',
        totalSeats: 38,
        totalWindowSeatsAvailable: 24,
        rating: 4.5,
        animeties: ['Live Tracking', 'Policies', 'Photos', 'Amenities', 'Reviews'],
        "seats_details": [
            { no: 1, type: 'UW', price: 1000, is_reseved: false, is_clicked: false },
            { no: 2, type: 'UW', price: 1000, is_reseved: false, is_clicked: false },
            { no: 3, type: 'UW', price: 1000, is_reseved: false, is_clicked: false },
            { no: 4, type: 'UW', price: 1000, is_reseved: false, is_clicked: false },
            { no: 5, type: 'UW', price: 1000, is_reseved: false, is_clicked: false },
            { no: 6, type: 'UW', price: 1000, is_reseved: false, is_clicked: false },
            { no: 7, type: 'UW', price: 1000, is_reseved: false, is_clicked: false },
            { no: 8, type: 'US', price: 800, is_reseved: false, is_clicked: false },
            { no: 9, type: 'US', price: 800, is_reseved: false, is_clicked: false },
            { no: 10, type: 'US', price: 800, is_reseved: false, is_clicked: false },
            { no: 11, type: 'US', price: 800, is_reseved: false, is_clicked: false },
            { no: 12, type: 'US', price: 800, is_reseved: false, is_clicked: false },
            { no: 13, type: 'US', price: 800, is_reseved: false, is_clicked: false },
            { no: 14, type: 'US', price: 800, is_reseved: false, is_clicked: false },
            { no: 15, type: 'UW', price: 1000, is_reseved: false, is_clicked: false },
            { no: 16, type: 'UW', price: 1000, is_reseved: false, is_clicked: false },
            { no: 17, type: 'UW', price: 1000, is_reseved: false, is_clicked: false },
            { no: 18, type: 'UW', price: 1000, is_reseved: false, is_clicked: false },
            { no: 19, type: 'UW', price: 1000, is_reseved: false, is_clicked: false },
            { no: 20, type: 'LW', price: 950, is_reseved: false, is_clicked: false },
            { no: 21, type: 'LW', price: 950, is_reseved: false, is_clicked: false },
            { no: 22, type: 'LW', price: 950, is_reseved: false, is_clicked: false },
            { no: 23, type: 'LW', price: 950, is_reseved: false, is_clicked: false },
            { no: 24, type: 'LW', price: 950, is_reseved: false, is_clicked: false },
            { no: 25, type: 'LW', price: 950, is_reseved: false, is_clicked: false },
            { no: 26, type: 'LW', price: 950, is_reseved: false, is_clicked: false },
            { no: 27, type: 'LS', price: 770, is_reseved: false, is_clicked: false },
            { no: 28, type: 'LS', price: 770, is_reseved: false, is_clicked: false },
            { no: 29, type: 'LS', price: 770, is_reseved: false, is_clicked: false },
            { no: 30, type: 'LS', price: 770, is_reseved: false, is_clicked: false },
            { no: 31, type: 'LS', price: 770, is_reseved: false, is_clicked: false },
            { no: 32, type: 'LS', price: 770, is_reseved: false, is_clicked: false },
            { no: 33, type: 'LS', price: 770, is_reseved: false, is_clicked: false },
            { no: 34, type: 'LW', price: 950, is_reseved: false, is_clicked: false },
            { no: 35, type: 'LW', price: 950, is_reseved: false, is_clicked: false },
            { no: 36, type: 'LW', price: 950, is_reseved: false, is_clicked: false },
            { no: 37, type: 'LW', price: 950, is_reseved: false, is_clicked: false },
            { no: 38, type: 'LW', price: 950, is_reseved: false, is_clicked: false }
        ]
    },
    {
        name: 'Neeta Travels',
        category: 'A/C Sleeper (2+1)',
        totalSeats: 38,
        totalWindowSeatsAvailable: 24,
        rating: 4.5,
        animeties: ['Live Tracking', 'Policies', 'Photos', 'Amenities', 'Reviews'],
        "seats_details": [
            { no: 1, type: 'UW', price: 950, is_reseved: false, is_clicked: false },
            { no: 2, type: 'UW', price: 950, is_reseved: false, is_clicked: false },
            { no: 3, type: 'UW', price: 950, is_reseved: false, is_clicked: false },
            { no: 4, type: 'UW', price: 950, is_reseved: false, is_clicked: false },
            { no: 5, type: 'UW', price: 950, is_reseved: false, is_clicked: false },
            { no: 6, type: 'UW', price: 950, is_reseved: false, is_clicked: false },
            { no: 7, type: 'UW', price: 950, is_reseved: false, is_clicked: false },
            { no: 8, type: 'US', price: 800, is_reseved: false, is_clicked: false },
            { no: 9, type: 'US', price: 800, is_reseved: false, is_clicked: false },
            { no: 10, type: 'US', price: 800, is_reseved: false, is_clicked: false },
            { no: 11, type: 'US', price: 800, is_reseved: false, is_clicked: false },
            { no: 12, type: 'US', price: 800, is_reseved: false, is_clicked: false },
            { no: 13, type: 'US', price: 800, is_reseved: false, is_clicked: false },
            { no: 14, type: 'US', price: 800, is_reseved: false, is_clicked: false },
            { no: 15, type: 'UW', price: 950, is_reseved: false, is_clicked: false },
            { no: 16, type: 'UW', price: 950, is_reseved: false, is_clicked: false },
            { no: 17, type: 'UW', price: 950, is_reseved: false, is_clicked: false },
            { no: 18, type: 'UW', price: 950, is_reseved: false, is_clicked: false },
            { no: 19, type: 'UW', price: 950, is_reseved: false, is_clicked: false },
            { no: 20, type: 'LW', price: 950, is_reseved: false, is_clicked: false },
            { no: 21, type: 'LW', price: 950, is_reseved: false, is_clicked: false },
            { no: 22, type: 'LW', price: 950, is_reseved: false, is_clicked: false },
            { no: 23, type: 'LW', price: 950, is_reseved: false, is_clicked: false },
            { no: 24, type: 'LW', price: 950, is_reseved: false, is_clicked: false },
            { no: 25, type: 'LW', price: 950, is_reseved: false, is_clicked: false },
            { no: 26, type: 'LW', price: 950, is_reseved: false, is_clicked: false },
            { no: 27, type: 'LS', price: 750, is_reseved: false, is_clicked: false },
            { no: 28, type: 'LS', price: 750, is_reseved: false, is_clicked: false },
            { no: 29, type: 'LS', price: 750, is_reseved: false, is_clicked: false },
            { no: 30, type: 'LS', price: 750, is_reseved: false, is_clicked: false },
            { no: 31, type: 'LS', price: 750, is_reseved: false, is_clicked: false },
            { no: 32, type: 'LS', price: 750, is_reseved: false, is_clicked: false },
            { no: 33, type: 'LS', price: 750, is_reseved: false, is_clicked: false },
            { no: 34, type: 'LW', price: 950, is_reseved: false, is_clicked: false },
            { no: 35, type: 'LW', price: 950, is_reseved: false, is_clicked: false },
            { no: 36, type: 'LW', price: 950, is_reseved: false, is_clicked: false },
            { no: 37, type: 'LW', price: 950, is_reseved: false, is_clicked: false },
            { no: 38, type: 'LW', price: 950, is_reseved: false, is_clicked: false }
        ]
    }
]

function createData(from_str, fromState_str, to_str, toState_str,date_d) {
    let newData = []

    for (let i = 0; i < 10; i++) {
        let s = strToTimeSpan(x[i].startTime)
        let e = strToTimeSpan(x[i].endTime)
        newData.push({ startTime: s, endTime: e, date: date_d, from: from_str, fromState: fromState_str, to: to_str, toState: toState_str, ...data[i] })
    }


    
    try {
            const result = bus.insertMany(newData)
            console.log(`${result.insertedCount} documents were inserted`);
       
    } catch (err) {
        console.log(err)
    }

}


module.exports = createData







